# Generated by Django 5.2.2 on 2026-07-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0007_alter_mark_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin'), ('store_owner', 'StoreOwner')], default='student', max_length=20),
        ),
    ]
