# Generated by Django 5.2.2 on 2026-03-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_shop_point_a_lat_shop_point_a_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('kg', 'Кыргызский'), ('en', 'Английский'), ('cn', 'Китайский')], default='ru', max_length=2, verbose_name='Язык'),
        ),
    ]
