# Generated by Django 5.2.2 on 2026-03-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_client_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_cn',
            field=models.CharField(default=' ', max_length=100, verbose_name='Название категории (кит)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(default='empty', max_length=100, verbose_name='Название категории (англ)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='name_kg',
            field=models.CharField(default=0, max_length=100, verbose_name='Название категории (кырг)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='description_cn',
            field=models.TextField(blank=True, null=True, verbose_name='Описание товара (кит)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание товара (англ)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_kg',
            field=models.TextField(blank=True, null=True, verbose_name='Описание товара (кырг)'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_cn',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название товара (кит)'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название товара (англ)'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_kg',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название товара (кырг)'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_cn',
            field=models.TextField(blank=True, null=True, verbose_name='Описание услуги (кит)'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание услуги (англ)'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_kg',
            field=models.TextField(blank=True, null=True, verbose_name='Описание услуги (кырг)'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_cn',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название услуги (кит)'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название услуги (англ)'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_kg',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название услуги (кырг)'),
        ),
        migrations.AddField(
            model_name='shop',
            name='description_cn',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (кит)'),
        ),
        migrations.AddField(
            model_name='shop',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (англ)'),
        ),
        migrations.AddField(
            model_name='shop',
            name='description_kg',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (кырг)'),
        ),
    ]
