# Generated by Django 5.2.2 on 2026-03-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_category_name_cn_category_name_en_category_name_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Фото товара'),
        ),
    ]
