# Generated by Django 5.2.2 on 2026-04-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_remove_product_image_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Изображения'),
        ),
    ]
