# Generated by Django 5.2.2 on 2026-04-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_alter_productimage_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='next_subscription_disable',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда кончается безлимит'),
        ),
    ]
