# Generated by Django 5.2.2 on 2026-07-11 04:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_client_next_subscription_disable'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Баланс (сом / тезики)'),
        ),
    ]
