# Generated by Django 5.2.2 on 2026-07-11 19:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_client_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_slug', models.CharField(max_length=100, verbose_name='Категория объявления')),
                ('subcategory_slug', models.CharField(max_length=100, verbose_name='Подкатегория объявления')),
                ('name', models.CharField(max_length=200, verbose_name='Название объявления')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('status_label', models.CharField(blank=True, default='', max_length=100, verbose_name='Тип объявления (подпись)')),
                ('show_phone', models.BooleanField(default=False, verbose_name='Показывать телефон')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена (KGS)')),
                ('channel_id', models.BigIntegerField(verbose_name='ID канала')),
                ('message_id', models.BigIntegerField(verbose_name='ID сообщения')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('inactive', 'Неактивный')], default='active', max_length=20, verbose_name='Статус объявления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='client.client', verbose_name='Владелец объявления')),
            ],
            options={
                'verbose_name': 'Объявление клиента',
                'verbose_name_plural': 'Объявления клиентов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='client.clientad', verbose_name='Избранные объявления'),
        ),
        migrations.CreateModel(
            name='TeziksTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transactions', to='client.client', verbose_name='Получатель')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_transactions', to='client.client', verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Транзакция тезиков',
                'verbose_name_plural': 'Транзакции тезиков',
                'ordering': ['-created_at'],
            },
        ),
    ]
