# Generated by Django 5.2.2 on 2026-07-13 16:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0019_clientad_client_favorites_tezikstransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientad',
            name='currency',
            field=models.CharField(default='KGS', max_length=10, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='clientad',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена'),
        ),
    ]
