# Generated by Django 5.2.2 on 2026-07-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0020_clientad_currency_alter_clientad_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientad',
            name='full_message_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='ID сообщений в канале'),
        ),
    ]
