# Generated by Django 5.2.2 on 2026-07-13 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_type', models.CharField(choices=[('market_bot', 'TEZZ Market Bot')], default='market_bot', max_length=30, verbose_name='Тип')),
                ('name', models.CharField(max_length=100, verbose_name='Название (рус)')),
                ('name_en', models.CharField(blank=True, default='', max_length=100, verbose_name='Название (англ)')),
                ('name_kg', models.CharField(blank=True, default='', max_length=100, verbose_name='Название (кырг)')),
                ('name_cn', models.CharField(blank=True, default='', max_length=100, verbose_name='Название (кит)')),
                ('emoji', models.CharField(blank=True, default='', max_length=8, verbose_name='Эмодзи')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Категория FAQ',
                'verbose_name_plural': 'FAQ · Категории',
                'ordering': ['app_type', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос (рус)')),
                ('question_en', models.CharField(blank=True, default='', max_length=255, verbose_name='Вопрос (англ)')),
                ('question_kg', models.CharField(blank=True, default='', max_length=255, verbose_name='Вопрос (кырг)')),
                ('question_cn', models.CharField(blank=True, default='', max_length=255, verbose_name='Вопрос (кит)')),
                ('answer', models.TextField(verbose_name='Ответ (рус)')),
                ('answer_en', models.TextField(blank=True, default='', verbose_name='Ответ (англ)')),
                ('answer_kg', models.TextField(blank=True, default='', verbose_name='Ответ (кырг)')),
                ('answer_cn', models.TextField(blank=True, default='', verbose_name='Ответ (кит)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='faq.faqcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Вопрос-ответ',
                'verbose_name_plural': 'FAQ · Вопросы-ответы',
                'ordering': ['category', 'order', 'id'],
            },
        ),
    ]
